# Copyright 2020 Erik Lönroth
# See LICENSE file for licensing details.
#
# This is only an example, and you should edit to suit your needs.
# If you don't need config, you can remove the file entirely.
options:
  fqdn:
    type: string
    default: ""
    description: >
      FQDN of Nextcloud instance
  port:
    type: int
    description: >
      Port where the Nextcloud website will be listening.
  php_max_file_uploads:
    type: int
    default: 20
    description: >
      Setting for php
  php_upload_max_filesize:
    type: string
    default: '512M'
    description: >
      Setting for php
  php_post_max_size:
    type: string
    default: '512M'
    description: >
      Setting for php
  php_memory_limit:
    type: string
    default: '1G'
    description: >
      Setting for php
  nextcloud-tarfile:
    type: string
    default: https://download.nextcloud.com/server/releases/nextcloud-23.0.0.tar.bz2
    description: >
      Sources for nextcloud (must be tar.bz2)
  overwriteprotocol:
    type: string
    default: http
    description: >
      Set this to https if you place a ssl-termination proxy in front of your nextcloud instance.
  backup-host:
    type: string
    default: ''
    description: >
      Host where to send backups.
  backup-slack-webhook:
    type: string
    default: ''
    description: >
      Webhook to Slack channel for sending backup status.
  backup-pagerduty-serviceid:
    type: string
    default: ''
    description: >
      PagerDuty service ID for backup failure alarms.
  backup-pagerduty-token:
    type: string
    default: ''
    description: >
      PagerDuty token for backup failure alarms.
  backup-pagerduty-email:
    type: string
    default: ''
    description: >
      PagerDuty service email for backup failure alarms.
