# Builds libs, charm and runs unittests on ubuntu bionic.
name: Nextcloud charm

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: "Prepare OS for builds and unittests"
      run: |
        sudo apt-get install -y python3-setuptools python3-wheel
    - name: "make nextcloud-lib"
      run: |
        make build-lib
        # Successful build created: lib/dist/nextcloud-0.0.1-py3-none-any.whl
        # We copy that to the nextcloud-charm which it needs in its requirements.txt.
        mkdir -p charm-nextcloud/lib/dist/
        cp lib/dist/nextcloud-0.0.1-py3-none-any.whl charm-nextcloud/lib/dist/

    - name: Unittest nextcloud
      run: |
        #TODO: some of this should be moved to requireents-dev.txt
        
        # Install ...
        cd charm-nextcloud
        pip3 install wheel
        pip3 install -r requirements.txt
        pip3 install -r requirements-dev.txt
        
        sudo ./run_tests
