# Builds and runs unittests on ubuntu bionic.
name: Nextcloud charm (charmcraft)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: "Prepare OS for builds and unittests"
      run: |
        sudo apt-get install -y python3-setuptools python3-wheel

    - name: Linting
      run: |
        make lint

    - name: Unittest nextcloud
      run: |
        #TODO: some of this should be moved to requirements-dev.txt
        
        # Install ...
        cd operator-nextcloud
        sudo pip3 install wheel
        sudo pip3 install -r requirements.txt
        sudo pip3 install -r requirements-dev.txt

        # preserve environment since we also run functional tests here needing root but also env.
        sudo -preserve-env ./run_tests
